### ISSUE TITLE
Installing V8 R package in a Conda Environment

### ISSUE THREAD

**Issue by sreedta8** [jeroen/V8#102]
Sytem and Software specifications:

1. OS: Ubuntu 20.04

2.  Python via Anaconda 64-bit: Using both versions 3.8 and 3.6

3. R (installed via Conda):  as r-base version 3.6.1

4. V8 packages: tried V8_2.3.tar.gz and V8_3.2.tar.gz (tried to install both as local files and from CRAN mirrors)

5. Ubuntu has **libnode-dev* already installed

6. I also installed **libv8** from Anaconda channel

I get the following error in bold text. I'm posting the entire compilation output for reference. It compiles okay and fails when testing to check if the library can be loaded from the temporary location.

> install.packages("V8")
--- Please select a CRAN mirror for use in this session ---
trying URL 'https://cloud.r-project.org/src/contrib/V8_3.2.0.tar.gz'
Content type 'application/x-gzip' length 680510 bytes (664 KB)

downloaded 664 KB

- installing *source* package ‘V8’ ...
- package ‘V8’ successfully unpacked and MD5 sums checked
- using staged installation
Using PKG_CFLAGS=-I/usr/include/v8 -I/usr/include/v8-3.14
Using PKG_LIBS=-lv8 -lv8_libplatform
Running feature test for pointer compression...
Pointer compression not needed
- libs
rm -f V8.so RcppExports.o bindings.o
x86_64-conda_cos6-linux-gnu-c++ -std=gnu++11 -I"/home/dattazs/miniconda3/envs/randpy/lib/R/include" -DNDEBUG -I/usr/include/v8 -I/usr/include/v8-3.14 -DV8_ENABLE_CHECKS -I"/home/dattazs/miniconda3/envs/randpy/lib/R/library/Rcpp/include" -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem /home/dattazs/miniconda3/envs/randpy/include -I/home/dattazs/miniconda3/envs/randpy/include -Wl,-rpath-link,/home/dattazs/miniconda3/envs/randpy/lib -fvisibility=hidden -fpic  -fvisibility-inlines-hidden  -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /home/dattazs/miniconda3/envs/randpy/include -fdebug-prefix-map=/tmp/build/80754af9/r-base_1589917437985/work=/usr/local/src/conda/r-base-3.6.1 -fdebug-prefix-map=/home/dattazs/miniconda3/envs/randpy=/usr/local/src/conda-prefix  -c RcppExports.cpp -o RcppExports.o
x86_64-conda_cos6-linux-gnu-c++ -std=gnu++11 -I"/home/dattazs/miniconda3/envs/randpy/lib/R/include" -DNDEBUG -I/usr/include/v8 -I/usr/include/v8-3.14 -DV8_ENABLE_CHECKS -I"/home/dattazs/miniconda3/envs/randpy/lib/R/library/Rcpp/include" -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem /home/dattazs/miniconda3/envs/randpy/include -I/home/dattazs/miniconda3/envs/randpy/include -Wl,-rpath-link,/home/dattazs/miniconda3/envs/randpy/lib -fvisibility=hidden -fpic  -fvisibility-inlines-hidden  -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /home/dattazs/miniconda3/envs/randpy/include -fdebug-prefix-map=/tmp/build/80754af9/r-base_1589917437985/work=/usr/local/src/conda/r-base-3.6.1 -fdebug-prefix-map=/home/dattazs/miniconda3/envs/randpy=/usr/local/src/conda-prefix  -c bindings.cpp -o bindings.o
x86_64-conda_cos6-linux-gnu-c++ -std=gnu++11 -shared -L/home/dattazs/miniconda3/envs/randpy/lib/R/lib -Wl,-O2 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now -Wl,--disable-new-dtags -Wl,--gc-sections -Wl,-rpath,/home/dattazs/miniconda3/envs/randpy/lib -Wl,-rpath-link,/home/dattazs/miniconda3/envs/randpy/lib -L/home/dattazs/miniconda3/envs/randpy/lib -L/home/dattazs/miniconda3/envs/randpy/lib -Wl,-rpath-link,/home/dattazs/miniconda3/envs/randpy/lib -o V8.so RcppExports.o bindings.o -lv8 -lv8_libplatform -L/home/dattazs/miniconda3/envs/randpy/lib/R/lib -lR
installing to /home/dattazs/miniconda3/envs/randpy/lib/R/library/00LOCK-V8/00new/V8/libs
- R
- inst
- byte-compile and prepare package for lazy loading
- help
- installing help indices
- building package indices
- installing vignettes
- testing if installed package can be loaded from temporary location
Error: package or namespace load failed for ‘V8’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/home/dattazs/miniconda3/envs/randpy/lib/R/library/00LOCK-V8/00new/V8/libs/V8.so':
  /home/dattazs/miniconda3/envs/randpy/lib/R/library/00LOCK-V8/00new/V8/libs/V8.so: **undefined symbol:** **_ZN2v82V813DisposeGlobalEPPNS_8internal6ObjectE**
Error: loading failed
Execution halted
ERROR: loading failed
removing ‘/home/dattazs/miniconda3/envs/randpy/lib/R/library/V8’

The downloaded source packages are in
        ‘/tmp/RtmpeoC9sK/downloaded_packages’
Updating HTML index of packages in '.Library'
Making 'packages.html' ... done
Warning message:
In install.packages("V8") :
  installation of package ‘V8’ had non-zero exit status.

I have reinstalled Rcppand tried to run install.packages() againbut without success.

What can and what should I do to get this correct?

Sree

**Comment by jeroen** [comment]
Can you just install [r-v8](https://anaconda.org/conda-forge/r-v8) from conda forge?

**Comment by sreedta8** [comment]
Thanks for the quick reply. I'm a bit of a newbie on the Ubuntu side and I did not check thoroughly for this at Anaconda. I will let you know how it goes @jeroen

**Comment by sreedta8** [comment]
@jeroen  thank you so much - it worked exactly as it should. I have been working with @adamhaber, who has developed a Python front end called **pybrms** (hosted on GitHub) to *brms* a very good Bayesian modeling package in R (which itself is a front end to Stan probabilistic language). I have been working on setting up *pybrms* on both Windows and Ubuntu OS. On the Ubuntu side is where I ran into a lot of issues. I cannot thank you enough - my environment with *rpy2*, *R*,and *pybrms* is working now on Ubuntu
