### ISSUE TITLE
Installation on openSUSE

### ISSUE THREAD

**Issue by long39ng** [jeroen/V8#103]
Hi, I haven't been able to install V8 on openSUSE Leap 15.2. I tried installing NodeJS and pointing the INCLUDE_DIR to where v8.h is installed (/usr/include/node12/), but was not successful:

```
Found INCLUDE_DIR and/or LIB_DIR!
Using PKG_CFLAGS=-I/usr/include/node12/ -I/usr/include/v8 -I/usr/include/v8-3.14
Using PKG_LIBS=-L -lv8 -lv8_libplatform
Running feature test for pointer compression...
/usr/lib64/gcc/x86_64-suse-linux/7/../../../../x86_64-suse-linux/bin/ld: cannot find -lv8_libplatform
collect2: error: ld returned 1 exit status
Enabling pointer compression
** libs
rm -f V8.so RcppExports.o bindings.o
g++ -std=gnu++11 -I"/opt/R/4.0.3/lib/R/include" -DNDEBUG -I/usr/include/node12/ -I/usr/include/v8 -I/usr/include/v8-3.14 -DV8_COMPRESS_POINTERS -I'/home/long/R/x86_64-pc-linux-gnu-library/4.0/Rcpp/include' -I/usr/local/include  -fvisibility=hidden -fpic  -g -O2  -c RcppExports.cpp -o RcppExports.o
g++ -std=gnu++11 -I"/opt/R/4.0.3/lib/R/include" -DNDEBUG -I/usr/include/node12/ -I/usr/include/v8 -I/usr/include/v8-3.14 -DV8_COMPRESS_POINTERS -I'/home/long/R/x86_64-pc-linux-gnu-library/4.0/Rcpp/include' -I/usr/local/include  -fvisibility=hidden -fpic  -g -O2  -c bindings.cpp -o bindings.o
g++ -std=gnu++11 -shared -L/opt/R/4.0.3/lib/R/lib -L/usr/local/lib -o V8.so RcppExports.o bindings.o -L -lv8 -lv8_libplatform -L/opt/R/4.0.3/lib/R/lib -lR
/usr/lib64/gcc/x86_64-suse-linux/7/../../../../x86_64-suse-linux/bin/ld: cannot find -lv8_libplatform
collect2: error: ld returned 1 exit status
make: *** [/opt/R/4.0.3/lib/R/share/make/shlib.mk:10: V8.so] Error 1
ERROR: compilation failed for package ‘V8’
```

I guess the problem is similar to #94, where NodeJS is built without the `--shared` option. As I'm still new to Linux, I am rather reserved about building it from source. I would be grateful for your suggestions.

**Comment by gsgxnet** [comment]
Hi,

I have the same problem under openSUSE Tumbleweed. No way to install `rstan` or `brms` or ... because they all need v8 libs. 

After some looking around I managed to `git clone depot_tools`. And with them I was able to `fetch v8` sources. But I have no clue at all how to build the v8 devel libs out of that. Is there any `make` hiding? I did not find anything. So I am stuck.

**Comment by JanMarvin** [comment]
@gsgxnet since I haven't used opensuse, I'd assume you can use the same args I use for Arch Linux

**Comment by gsgxnet** [comment]
> @gsgxnet since I haven't used opensuse, I'd assume you can use the same args I use for Arch Linux

yes that worked to manually compile and install the libs and the include files. Installation of the V8 R package still fails, this time with compile errors caused by the include:

```
* installing *source* package ‘V8’ ...
** Paket ‘V8’ erfolgreich entpackt und MD5 Summen überprüft
** using staged installation
Using PKG_CFLAGS=-I/usr/include/v8 -I/usr/include/v8-3.14
Using PKG_LIBS=-lv8 -lv8_libplatform
Running feature test for pointer compression...
In file included from /usr/local/include/v8.h:30,
                 from tools/test.cpp:2:
/usr/local/include/v8-internal.h: In function ‘void v8::internal::PerformCastCheck(T*)’:
/usr/local/include/v8-internal.h:450:38: error: ‘remove_cv_t’ is not a member of ‘std’; did you mean ‘remove_cv’?
  450 |             !std::is_same<Data, std::remove_cv_t<T>>::value>::Perform(data);
      |                                      ^~~~~~~~~~~
      |                                      remove_cv
```
and so on. May be a version mismatch

**Comment by JanMarvin** [comment]
install from the master branch of Jeroen/V8. it's already fixed

**Comment by gsgxnet** [comment]
> yes that worked to manually compile and install the libs and the include files. 

To document how the v8 libs compile can be manually done on openSUSE these steps led to a successful compile:

V8 can not easily be installed from github sources or similar. 
The buildsystem of v8 is based on depot-tools.

So:
choose a place for building v8
`cd <home-working dir>`  
get the build environment, depot tools:  
`git clone https://chromium.googlesource.com/chromium/tools/depot_tools`

```
export PATH=`pwd`/depot_tools:"$PATH"
```
`cd depot_tools`  

`fetch v8`  
if that fails in between or for later updates use to repair/update:  
`gclient sync`  

`export OUTFLD=suselibs`

`cd v8`

```
gn gen $OUTFLD     -vv --fail-on-unused-args     --args='clang_base_path="/usr/"
    is_clang=false
    is_asan=false
    use_gold=false
    clang_use_chrome_plugins=false
    is_component_build=true
    is_debug=false
    is_official_build=false
    treat_warnings_as_errors=false
    v8_enable_i18n_support=true
    v8_use_external_startup_data=false
    use_custom_libcxx=false
    use_sysroot=false'
```

`ninja -C $OUTFLD`

copy the built libs and includes into the right folders in the filesystem

from `<depot-tools-path>/v8/$OUTFLD`
`cp -a {d8,libv8.so,libv8_libbase.so,libv8_libplatform.so,libchrome_zlib.so} /usr/local/lib64`

from `<depot-tools-path>/v8/includes`  
```
cp -a *.h /usr/local/include
cp -a /cppgc /usr/local/include
cp -a /libplatform /usr/local/include
```

`export PATH=${PATH#*:}`

this is at the moment not a full fledged working script for building v8 libs, just a record of the steps I did manually to get it going. So anybody trying to compile should follow it step by step and check whether the step was formulated right and you get the right results.

**Comment by gsgxnet** [comment]
> install from the master branch of Jeroen/V8. it's already fixed

will do,  
but I think in the long run we have to find a way to have a successful 3 step (depot-tools, v8 libs, v8 R package)buildprocess working on SUSE. So I would like to iron out the problems.

**Comment by gsgxnet** [comment]
> install from the master branch of Jeroen/V8. it's already fixed

did so. works: https://github.com/jeroen/V8/issues/94#issuecomment-715634673

**Comment by JanMarvin** [comment]
thanks for the confirmation that the static build works for you. though what I meant with my comment above was: the build error you're seeing above is due to an already closed issue regarding c++14 in the R package V8. until the next release is pushed to cran, your should be able to install it with 
```{R}
devtools::install_github("Jeroen/v8")
```
this should enable V8 with the version you build in the steps above.

if you want to tweak things further (regarding your own dynamic build), you might want to look into package building. since every distribution handles things differently you'd have to figure out how spec files for rpms look like. building v8 is not always straight forward, but it's also not impossible. for inspiration you might have a look at the chromium builds for your distribution and adapt from there on.

**Comment by jeroen** [comment]
I'll do a cran release today to get that part out of the way at least...

**Comment by gsgxnet** [comment]
> ```
> devtools::install_github("Jeroen/v8")
> ```
> 
> 
> this should enable V8 with the version you build in the steps above.

at the moment that kind of install of V8 (R) fails here:

```
Fehler: Failed to install 'V8' from GitHub:
  System command 'R' failed, exit status: 1, stdout + stderr (last 10 lines):
E> ** R
E> ** inst
E> ** byte-compile and prepare package for lazy loading
E> ** help
E> Error :  kann shared object '/tmp/RtmpEHWfJm/Rinst2c8a790a2398/00LOCK-V8/00new/V8/libs/V8.so' nicht laden:
E>   libv8.so: cannot open shared object file: No such file or directory
E> ERROR: installing Rd objects failed for package ‘V8’
E> * removing ‘/tmp/RtmpEHWfJm/Rinst2c8a790a2398/V8’
E>       -----------------------------------
E> ERROR: package installation failed
```
v8 lib exists: 
`/usr/local/lib64/libv8.so`

**Comment by JanMarvin** [comment]
I'm not sure if that path is in the configure for v8 (I only use `/usr/lib`) and you might check what `ldd usr/local/lib64/libv8.so` returns (e.g., if you have all the libs in place)

**Comment by jeroen** [comment]
@gsgxnet if you install `libv8.so` anywhere else then `/usr/local` then you need to set an environment variable LD_LIBRARY_PATH when loading the R package. E.g. you can do this in your `~/.Renviron` file. Or you can run

```sh
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:usr/local/lib64
sudo ldconfig
```

**Comment by gsgxnet** [comment]
@jeroen you were partially right.

> ```shell
> export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:usr/local/lib64
> sudo ldconfig
> ```

`LD_LIBRARY_PATH` is in SUSE is a nono nowdays. To configure the extra library paths needed locally they have to have entries in `/etc/ld.so.conf`.  
`/usr/local/lib64` is in there since a long time here. 
BUT after having added the new lib files to `/usr/local/lib64` i forgot to execute `ldconfig`.
After doing so listing the ld cache
```
ldconfig -p | grep v8
        libv8_libplatform.so (libc6,x86-64) => /usr/local/lib64/libv8_libplatform.so
        libv8_libbase.so (libc6,x86-64) => /usr/local/lib64/libv8_libbase.so
        libv8.so (libc6,x86-64) => /usr/local/lib64/libv8.so
```
shows the relevant libs are found, and now
`devtools::install_github("Jeroen/v8")` succeeds. 

THANKS!
`

**Comment by jeroen** [comment]
Added an option to the master branch to automatically download libv8. This should allow installation on any Linux system with at least gcc-5. To use this in R:

```r
Sys.setenv(DOWNLOAD_STATIC_LIBV8 = 1)
remotes::install_github("jeroen/V8")
```

**Comment by long39ng** [comment]
Thank you so much!

**Comment by jeroen** [comment]
This is now on CRAN. You can now install V8 on any 64-bit Linux using:

```r
Sys.setenv(DOWNLOAD_STATIC_LIBV8 = 1)
install.packages("V8")
```
