### ISSUE TITLE
‘V8’ is not available (for R version 4.0.2) 

### ISSUE THREAD

**Issue by MartinBulla** [jeroen/V8#111]
Dear V8 team,

I am getting ‘V8’ is not available (for R version 4.0.2) ' when trying installing V8 on 'R 4.0.2 (2020-06-22) -- "Taking Off Again" on Mac.

When do you expect to upgrade the V8?

Best,
Martin

**Comment by jeroen** [comment]
It's not unavailable, but it just got updated. You probably need to refresh your cache. Which operating system are you on?

**Comment by MartinBulla** [comment]
Thanks Jeroen. It works now.
