### ISSUE TITLE
Configuration failed to find the libv8 engine library

### ISSUE THREAD

**Issue by dudugang** [jeroen/V8#112]
I am trying to install package "V8",and I have installed the libnode-dev, but it still failed like this
![v8](https://user-images.githubusercontent.com/29590272/99929642-e6728880-2d88-11eb-9d93-69ed79b8448b.png)

**Comment by jeroen** [comment]
It says `g++ error: unrecognized command line option -O3`

That is not coming form V8. Do you have something weird in your personal `~/.R/Makevars` file?

**Comment by dudugang** [comment]
> It says `g++ error: unrecognized command line option -O3`
> 
> That is not coming form V8. Do you have something weird in your personal `~/.R/Makevars` file?

Well I am new in linux and I run this on debian under wsl2 for the first time,  I cannot find the makevars, where is it? or I have to creat it?

**Comment by dudugang** [comment]
> > It says `g++ error: unrecognized command line option -O3`
> > That is not coming form V8. Do you have something weird in your personal `~/.R/Makevars` file?
> 
> Well I am new in linux and I run this on debian under wsl2 for the first time, I cannot find the makevars, where is it? or I have to creat it?

Now I did this as follows:
![1](https://user-images.githubusercontent.com/29590272/100053309-beebf080-2e5a-11eb-908d-395e8588fc0e.png)
and try to install V8 again, results:
![2](https://user-images.githubusercontent.com/29590272/100053341-d2975700-2e5a-11eb-8bdc-f054429f8750.png)

**Comment by jeroen** [comment]
Can you try

```r
Sys.setenv(DOWNLOAD_STATIC_V8=1)
install.packages("V8")
```

**Comment by dudugang** [comment]
> Can you try
> 
> ```r
> Sys.setenv(DOWNLOAD_STATIC_V8=1)
> install.packages("V8")
> ```

Well, it works, the V8 package is installed successfully by using this method, thank you!
