### ISSUE TITLE
Error in V8 installation

### ISSUE THREAD

**Issue by laurabalasso** [jeroen/V8#114]
I'm trying to install V8 in a Linux cluster to be able to install Rstan. 
In R I run 

`Sys.setenv(DOWNLOAD_STATIC_LIBV8 = 1)`
`remotes::install_github("jeroen/V8")`

and I get the following error 

/usr/bin/ld: cannot find -lv8_monolith

Same thing happens if I install it directly from CRAN. Any clue about what's happening?

**Comment by jeroen** [comment]
Can you please show the full build log, and tell me which linux you use (`sessionInfo()`)

**Comment by laurabalasso** [comment]
> Can you please show the full build log, and tell me which linux you use (`sessionInfo()`)

This is the session info:

`> sessionInfo()
R version 4.0.1 (2020-06-06)
Platform: powerpc64le-unknown-linux-gnu (64-bit)
Running under: Red Hat Enterprise Linux Server 7.6 (Maipo)

Matrix products: default
BLAS:   /m100/prod/opt/libraries/blas/3.8.0/gnu--8.4.0/lib/libblas.so
LAPACK: /m100/prod/opt/applications/r/4.0.1/gnu--8.4.0/lib64/R/lib/libRlapack.so

locale:
 [1] LC_CTYPE=C                 LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_4.0.1
`

and here I attach the full build log (CRAN installation)

[V8_build_log.txt](https://github.com/jeroen/V8/files/5658189/V8_build_log.txt)

**Comment by jeroen** [comment]
Ah you run on powerpc hardware? Right now the download static method only works on x86_64.

An alternative method is to do: `sudo apt-get install v8-devel` and then __not__ set `DOWNLOAD_STATIC_LIBV8`, can you try this?

**Comment by laurabalasso** [comment]
I'm working on an HPC system where I don't have sudo permissions. I guess asking the admin to do it is the only solution (?)

**Comment by jeroen** [comment]
Yes I'm afraid so, I don't have a powerpc machine so I can't help. A simple `sudo yum install v8-devel` should do the job.
