### ISSUE TITLE
What does reset do?

### ISSUE THREAD

**Issue by SteveBronder** [jeroen/V8#121]
Sorry for the silly question but I saw it wasn't documented and looking at [the code](https://github.com/jeroen/V8/blob/581ec48c7be890c182d4125c5c119a857b45483c/R/V8.R#L194) I'm not familiar enough with v8 / javascript to know what's going on there

**Comment by jeroen** [comment]
This function initiates a v8 context when you run `v8()`, in particular assigns the `global` or `window` 

https://github.com/jeroen/V8/blob/581ec48c7be890c182d4125c5c119a857b45483c/R/V8.R#L253-L255
