### ISSUE TITLE
static V8 from local path

### ISSUE THREAD

**Issue by vandenman** [jeroen/V8#122]
I've been trying to install V8 using a local download of `http://jeroen.github.io/V8/v8-8.3.110.13-linux.tar.gz`, but somehow it's not working. Perhaps I'm doing something wrong, but I believe the problem is that the configure script changes additionally changes `-lv8 -lv8_libplatform` into `-lv8_monolith` when `DOWNLOAD_STATIC_LIBV8` is set. If I modify the configure script and overwrite `-lv8 -lv8_libplatform` with `-lv8_monolith` then the package installs fine.

Do you agree that the static version can only be used when the configure script also downloads the static V8 version?

If yes, I'd be happy to open a PR that allows this to be changed by passing an additional variable to the configure script.

Note: I'm doing this for a flatpak build script. When flatpak install an app, everything must be downloaded beforehand (there is no internet access) so the elegant solution with a static V8 does not work, unfortunately.

**Comment by jeroen** [comment]
> Do you agree that the static version can only be used when the configure script also downloads the static V8 version?

I don't understand what you mean.

**Comment by vandenman** [comment]
What I mean is, am I doing something wrong (which is certainly possible), or is it right now not possible to use the static version while setting the configure vars?

To replicate the problem:

1. Download and unpack http://jeroen.github.io/V8/v8-8.3.110.13-linux.tar.gz (basically, execute the steps in http://jeroen.github.io/V8/get-v8-linux.sh manually)
2. Install V8 with the configure vars set to the local path.
3. The installation fails.
