### ISSUE TITLE
Statically compiled V8 for ARM/aarch64

### ISSUE THREAD

**Issue by JorisGoosen** [jeroen/V8#124]
I'm trying to compile the static version of v8 so that we can use those on arm laptops.

I am going trough a process or trial-and-error trying to find the correct settings for it. BUt it would be quite helpful to know which settings were used to compile those at `http://jeroen.github.io/V8/v8-8.3.110.13-linux.tar.gz` etc.

I am now trying things like: `is_debug=false target_cpu="arm64" v8_target_cpu="arm64" use_goma=false v8_monolithic=true v8_use_external_startup_data=false v8_static_library=true v8_enable_i18n_support=false use_custom_libcxx=false`

Which made me run into another error, hopefully @jeroen can help me out sharing his incantation for v8?

Of course, even better would be to also have a static lib version there but I don't mind compiling it myself.

**Comment by jeroen** [comment]
Are you building for linux arm? This is how I built it: https://github.com/jeroen/build-v8-static. 
It would be great to add linux, but I don't have an arm linux box. Is this possible on dockerhub?

**Comment by JorisGoosen** [comment]
Yes I am, I dont know if it possible on dockerhub, but compiling v8 for it has to be done cross-compile anyway.
I do have a arm laptop to test on btw.

Thanks for the link, I will have a look!

**Comment by jeroen** [comment]
It looks like maybe docker can emulate these days. Trying this now: https://www.docker.com/blog/multi-arch-images/

**Comment by JorisGoosen** [comment]
Yeah, but you really don't need to run the docker in arm, in fact it is harder to use if I can believe https://blog.sqreen.com/how-we-built-v8-natively-on-arm/ . Which I do because the buildscripts from google pull in all sorts of x86 executables.

I am using the cross-compilation settings as v8 set it up for me, basically I did:
```
    git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
    export PATH=/path/to/depot_tools:$PATH
    fetch v8
    cd there
    gclient sync
    ./build/linux/sysroot_scripts/install-sysroot.py --arch=arm64
    gn gen monolithic/ --args='is_debug=false target_cpu="arm64" v8_target_cpu="arm64" use_goma=false v8_monolithic=true v8_use_external_startup_data=false'
    ninja -C monolithic v8_monolith 
```

But then of course with the build-arguments as you've used them.

**Comment by jeroen** [comment]
Does that assume a cross compiler is available on the system, or pull one in?

**Comment by jeroen** [comment]
By the way, which linux distro do you run? How did you end up with an arm laptop?

**Comment by JorisGoosen** [comment]
> Does that assume a cross compiler is available on the system, or pull one in?

It is pulled in by `./build/linux/sysroot_scripts/install-sysroot.py --arch=arm64` it looked like a debian img, not sure what all those scripts are doing though.

> By the way, which linux distro do you run? How did you end up with an arm laptop? Is this an apple M1?

I run arm manjaro on a [pinebook pro](https://www.pine64.org/pinebook-pro/) and also most arm chromebooks now support linux (via debian VM) so I will be testing on that later as well.

The weird thing is I can compile v8 with all the settings from your file but then linking it into V8 pkg gets me:
`V8.so: undefined symbol: _ZN2v816FunctionTemplate3NewEPNS_7IsolateEPFvRKNS_20FunctionCallbackInfoINS_5ValueEEEENS_5LocalIS4_EENSA_INS_9SignatureEEEiNS_19ConstructorBehaviorENS_14SideEffectTypeEPKNS_9CFunctionE` but haven't figured out yet why.

**Comment by jeroen** [comment]
It might be that the cross-compiler is newer than the native C++ compiler on your laptop. This is often a problem with static libraries, they may not be linkable with older compilers than what they were built for.

**Comment by jeroen** [comment]
It might be that the cross-compiler is newer than the native C++ compiler on your laptop. This is often a problem with static libraries, they may not be linkable with older compilers than what they were built for.

Also if the library was built with clang, it may not work for gcc. What version is your C++ compile on manjaro?

**Comment by JorisGoosen** [comment]
Yes this is probably the issue.

I had already made sure to build in gcc but it turns out that arch `x64` (where I work most of the time) installed gcc 11.1 for cross-compiling to `aarch64`. But arch/manjaro for arm is only up to gcc 10.2.

So I will try and get the older version for cross-compiling and see if that helps. I hadn't thought they would get out of synch as I'm used to arch always updating quickly.

**Comment by JorisGoosen** [comment]
Ok I tried it again, but now I used [aarch64-linux-gnu-gcc-10.2.0-1 from the arch linux archives](https://archive.archlinux.org/packages/a/aarch64-linux-gnu-gcc/aarch64-linux-gnu-gcc-10.2.0-1-x86_64.pkg.tar.zst).

I then cleaned and rebuild `v8` with `ninja` making sure it used `aarch64-linux-gnu-gcc` and using the following args: `is_debug=false target_cpu="arm64" v8_target_cpu="arm64" use_goma=false v8_monolithic=true v8_use_external_startup_data=false v8_enable_i18n_support=false use_custom_libcxx=false v8_expose_symbols=true is_clang=false is_asan=false use_gold=false v8_static_library=true is_official_build=false treat_warnings_as_errors=false use_sysroot=false`

However, using it in R on arm manjaro with gcc 10.2 still failed giving me the same error as before:
`V8.so: undefined symbol: _ZN2v816FunctionTemplate3NewEPNS_7IsolateEPFvRKNS_20FunctionCallbackInfoINS_5ValueEEEENS_5LocalIS4_EENSA_INS_9SignatureEEEiNS_19ConstructorBehaviorENS_14SideEffectTypeEPKNS_9CFunctionE`

Unless R is switching out `gcc` right from under my nose I assume something else must be missing. Because the compilers should be the same now at least.

**Comment by jeroen** [comment]
I'm giving it a go as well using the same docker scripts but with the cross compilers from Debian. Let's see if that works.

**Comment by jeroen** [comment]
I have added an arm64 binary and tried to update the download script: https://github.com/jeroen/V8/commit/23624bf3291aebda3dfc816b9c45075851ab825f

But I can't really test this because I don't have an arm box. Can you test if this works?

**Comment by JorisGoosen** [comment]
That seems to work great, at least it compiles and installs fine now.

Not sure how to know for sure it is used though (and thus see it work) or if that is already covered during any test during pkg install?

**Comment by jeroen** [comment]
If it installs then you're probably good. But to be sure you can start R and run:

```r
library(V8)
example(v8)
```

**Comment by JorisGoosen** [comment]
So yeah, it works great!

**Comment by jeroen** [comment]
OK thanks for confirming.

**Comment by JorisGoosen** [comment]
Thank you for helping me out.
