### ISSUE TITLE
V8 fails to build on PowerPC Mac with R 4.1.2

### ISSUE THREAD

**Issue by barracuda156** [jeroen/V8#132]
I tried setting static libv8, but it does not help:

> Sys.setenv(arch = "ppc")
> Sys.setenv(compiler = "gcc")
> Sys.setenv(stdlib = "libstdc++")
> Sys.setenv(DOWNLOAD_STATIC_LIBV8 = 1)
> install.packages("V8", type = "source")
Installing package into ‘/Users/svacchanda/Library/R/powerpc/4.1/library’
(as ‘lib’ is unspecified)
trying URL 'https://cran.csie.ntu.edu.tw/src/contrib/V8_3.6.0.tar.gz'
Content type 'application/octet-stream' length 794523 bytes (775 KB)
==================================================
downloaded 775 KB

Warning in file(con, "r") :
  cannot open file '/var/db/timezone/zoneinfo/+VERSION': No such file or directory
* installing *source* package ‘V8’ ...
** package ‘V8’ successfully unpacked and MD5 sums checked
** using staged installation
Not using CXX14
Using CXXCPP=/opt/local/bin/g++-mp-7 -E
Using PKG_CFLAGS=-I/usr/include/v8 -I/usr/include/v8-3.14
Using PKG_LIBS=-lv8 -lv8_libplatform
-----------------------------[ ANTICONF ]-------------------------------
Configuration failed to find the libv8 engine library. Try installing:
 * deb: libv8-dev or libnode-dev (Debian / Ubuntu)
 * rpm: v8-devel (Fedora, EPEL)
 * brew: v8 (OSX)
 * csw: libv8_dev (Solaris)
Alternatively, on Linux (x86_64) or MacOS you can set environment variable:
    DOWNLOAD_STATIC_LIBV8=1
to automatically download a static version of libv8.
To use a custom libv8, set INCLUDE_DIR and LIB_DIR manually via:
R CMD INSTALL --configure-vars='INCLUDE_DIR=... LIB_DIR=...'
---------------------------[ ERROR MESSAGE ]----------------------------
<stdin>:1:10: fatal error: v8.h: No such file or directory
compilation terminated.
------------------------------------------------------------------------
ERROR: configuration failed for package ‘V8’
* removing ‘/Users/svacchanda/Library/R/powerpc/4.1/library/V8’

The downloaded source packages are in
	‘/private/var/folders/rD/rDeCM6SDHv8daLCecrRmrU+++TI/-Tmp-/Rtmpu1cOE0/downloaded_packages’
Warning message:
In install.packages("V8", type = "source") :
  installation of package ‘V8’ had non-zero exit status
> 

> utils::sessionInfo()
R version 4.1.2 (2021-11-01)
Platform: powerpc-apple-darwin10.0.0d2 (32-bit)
Running under: OS X Snow Leopard 10.6

Matrix products: default
BLAS:   /opt/local/Library/Frameworks/R.framework/Versions/4.1/Resources/lib/libRblas.dylib
LAPACK: /opt/local/Library/Frameworks/R.framework/Versions/4.1/Resources/lib/libRlapack.dylib

locale:
[1] en_US.utf-8/en_US.utf-8/en_US.utf-8/C/en_US.utf-8/en_US.utf-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_4.1.2 tools_4.1.2

**Comment by jeroen** [comment]
The last version of MacOS that supported PPC was Mac OS X Leopard, which was released 14 years ago and EOL 11 years ago. So sadly I we not support this anymore.
