### ISSUE TITLE
Promise from `WebAssembly.compile()` never resolves

### ISSUE THREAD

**Issue by wch** [jeroen/V8#133]
This might be related to #131. `WebAssembly.compile()` returns a promise, but it never resolves. Here is an example:

```R
library(V8)
add_wasm <- readBin(system.file('wasm/add.wasm', package = 'V8'), "raw", 1e6)
ctx <- v8()
ctx$assign("add_wasm", add_wasm)
ctx$eval("ArrayBuffer.isView(add_wasm)")
ctx$eval("
let result = 'result not yet set';
WebAssembly.compile(add_wasm)
  .then((value) => {
    console.log('-> then');
    console.log(value);
    result = value;
  })
  .catch((err) => {
    console.log('-> catch');
    result = err;
    console.error(err);
  })
  .finally(() => {
    console.log('-> finally');
  });
")
#> [1] "[object Promise]"

# This should be a WebAssembly.Module, but for some reason V8 never gets to 
# the .then()
ctx$eval("result")
#> [1] "result not yet set"
```

I know there is the `wasm()` function, but for some reason it isn't working for the wasm binary I'm trying to run:

```R
pandoc_wasm <- readBin("https://y-taka-23.github.io/wasm-pandoc/wasm-pandoc.wasm", "raw", 1e8)
instance <- wasm(pandoc_wasm)
#> Error in context_eval(join(src), private$context, serialize) : 
#>   TypeError: WebAssembly.Instance(): Imports argument must be present and must be an object
```

This is the Pandoc wasm binary that is used in this online Pandoc converter:
  https://y-taka-23.github.io/wasm-pandoc/

Also, this particular wasm binary is meant to be wrapped in a lot of JavaScript, so I'm trying to load it the same way that they do it for the web app.

**Comment by jeroen** [comment]
Yes the problem is that our V8 interface returns immediately when the script completes, whereas the promise is resolved async. We may need to rewrite the interface to use an event-loop and for promises to resolve.

**Comment by jeroen** [comment]
https://docs.google.com/document/d/18vaABH1mR35PQr8XPHZySuQYgSjJbWFyAW63LW2m8-w/edit#
