### ISSUE TITLE
How to call `var iris = console.r.get("iris");` from node JS?

### ISSUE THREAD

**Issue by emmansh** [jeroen/V8#138]
I've just found this `V8` library and am trying to wrap my head around it. I want to call R _from_ node JS script. How should I do it?

I've tried to first open `R` and typed:
```r
library(V8)
ctx <- v8()
ctx$console()
```
<img width="378" alt="image" src="https://user-images.githubusercontent.com/18688877/151675785-aebcf40d-c9a0-4ee6-bbdd-dd36ed678d25.png">

Then, I opened a separate text editor and wrote a simple js command
```javascript
// in js
var iris = console.r.get("iris");
console.log(iris)
``` 
Then ran the script with `node`, and got:
> var iris = console.r.get("iris");
>                      ^
> 
> TypeError: Cannot read properties of undefined (reading 'get')
>     at Object.<anonymous>

Clearly, I'm missing something fundamental. How can I call `iris` _from_ node.js?

I read the vignettes (especially the [Callback to R](https://jeroen.cran.dev/V8/articles/v8_intro.html#callback-to-r) part) and googled around but couldn't figure this out. Any help would be appreciated!

**Comment by jeroen** [comment]
V8 in R is not connected to nodejs. The idea of that example is you paste that javascript code in the R temrinal, in the `ctx$console()` that you just opened.

**Comment by emmansh** [comment]
Snap, this is the answer I was afraid of. Could you point to a technique/method/framework that enables to call R from node js?

**Comment by jeroen** [comment]
If you run both on the same machine, you need an npm package that calls R. Maybe this one? https://www.npmjs.com/package/r-integration

If your R is running on a remote server, you could try something like opencpu or similar: https://www.npmjs.com/package/opencpu

**Comment by emmansh** [comment]
Thanks. Yeah I've seen `r-integration` but the problem is: calling R from node means it runs Rscript and parses the console print back into node. Which is hacky and prone to error. I'm looking for a more solid solution. `v8` indeed seemed to good to be true.
