### ISSUE TITLE
Installation Error about curl

### ISSUE THREAD

**Issue by DrDaedalusWHU** [jeroen/V8#154]
Dear jeroen,

I'm working on a CentOS 8 system, using R studio server (R version 4.1.3).
I followed the instruction and installed v8-devel using following command
`sudo yum --refresh install @nodejs:16-epel/minimal v8-devel `

Then I got:
`Package v8-devel-2:9.4.146.24-1.16.14.0.2.module_el8+13804+34326f90.x86_64 is already installed.
Dependencies resolved.
Nothing to do.
Complete!`

Then I opened my R studio server and tried to install V8 using
`install.packages("V8")`

I kept getting this error:

> install.packages("V8")
Installing package into ‘/home/huangkx/R/x86_64-pc-linux-gnu-library/4.1’
(as ‘lib’ is unspecified)
trying URL 'http://cran.rstudio.com/src/contrib/V8_4.2.1.tar.gz'
Content type 'application/x-gzip' length 682947 bytes (666 KB)
==================================================
downloaded 666 KB

* installing *source* package ‘V8’ ...
** package ‘V8’ successfully unpacked and MD5 sums checked
** using staged installation
Found C++17 compiler: g++
Target architecture: x86_64
Error in curl::curl_download("https://github.com/jeroen/V8/releases/download/v3.6.0/v8-9.6.180.12-amd64.tar.gz",  : 
  Timeout was reached: [] Connection timed out after 10000 milliseconds
Execution halted
tar (child): libv8.tar.gz: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
mv: cannot stat 'v8': No such file or directory
Using CXXCPP=g++ -std=gnu++17 -E
Using PKG_CFLAGS=-I/tmp/RtmpeT8XFV/R.INSTALL6199a205fd8a6/V8/.deps/include
Using PKG_LIBS=-L/tmp/RtmpeT8XFV/R.INSTALL6199a205fd8a6/V8/.deps/lib -lv8_monolith
Running feature test for pointer compression...
/usr/bin/ld: cannot find -lv8_monolith
collect2: error: ld returned 1 exit status
Enabling pointer compression
** libs
rm -f V8.so RcppExports.o bindings.o
g++ -std=gnu++17 -I"/opt/R/4.1.3/lib/R/include" -DNDEBUG -I/tmp/RtmpeT8XFV/R.INSTALL6199a205fd8a6/V8/.deps/include -DV8_COMPRESS_POINTERS -I'/home/huangkx/R/x86_64-pc-linux-gnu-library/4.1/Rcpp/include' -I/usr/local/include  -fvisibility=hidden -fpic  -g -O2  -c RcppExports.cpp -o RcppExports.o
g++ -std=gnu++17 -I"/opt/R/4.1.3/lib/R/include" -DNDEBUG -I/tmp/RtmpeT8XFV/R.INSTALL6199a205fd8a6/V8/.deps/include -DV8_COMPRESS_POINTERS -I'/home/huangkx/R/x86_64-pc-linux-gnu-library/4.1/Rcpp/include' -I/usr/local/include  -fvisibility=hidden -fpic  -g -O2  -c bindings.cpp -o bindings.o
g++ -std=gnu++17 -shared -L/opt/R/4.1.3/lib/R/lib -L/usr/local/lib -o V8.so RcppExports.o bindings.o -L/tmp/RtmpeT8XFV/R.INSTALL6199a205fd8a6/V8/.deps/lib -lv8_monolith -L/opt/R/4.1.3/lib/R/lib -lR
/usr/bin/ld: cannot find -lv8_monolith
collect2: error: ld returned 1 exit status
make: *** [/opt/R/4.1.3/lib/R/share/make/shlib.mk:10: V8.so] Error 1
ERROR: compilation failed for package ‘V8’
* removing ‘/home/huangkx/R/x86_64-pc-linux-gnu-library/4.1/V8’
Warning in install.packages :
  installation of package ‘V8’ had non-zero exit status

The downloaded source packages are in
	‘/tmp/RtmpfwTf6f/downloaded_packages’

I've tried changing the server DNS into 8.8.8.8 ,using proxy, setting longer curl timeout limits, and remove-reinstall v8-devel. None of them worked. The ERROR messages are the same as above.

So, I was wondering whether it was because of this
 “Error in curl::curl_download("https://github.com/jeroen/V8/releases/download/v3.6.0/v8-9.6.180.12-amd64.tar.gz",  : 
  Timeout was reached: [] Connection timed out after 10000 milliseconds” （DUE to internet connection and somehting like that）
 OR：
tar (child): libv8.tar.gz: Cannot open: No such file or directory
/usr/bin/ld: cannot find -lv8_monolith (DUE to libv8 related issues)

I've been stuck on this issue for several days. It would be greatly appreciated if you could provide some clues on solving this problem.

Best Regards.

**Comment by JerryZhang-1222** [comment]
Hello DrDaedalusWHU, I solved this issue with the help of VPN.

However, when setting the proxy after starting the VPN, you have to notice that `export http_proxy=http://proxyAddress:port`  only functions at the current termial, which means that the RStudioServer will not take this environment variable when you are running `install.packages()` in the IDE.

To soleve this, I downloaded the tar.gz file of V8 from CRAN(https://cran.r-project.org/web/packages/V8/index.html) in my PC using VPN again and uploaded to my server. Then I install the package with:
```
R CMD INSTALL -l R/lib/path unpacked/V8/path
```
which works fine for me.

You may also change the environment variables RStudioServer takes but I haven't figured that out yet.

**Comment by JanMarvin** [comment]
What happens if you run this?
```R
Sys.setenv(DOWNLOAD_STATIC_LIBV8 = 0)
install.packages("V8")
```

**Comment by jeroen** [comment]
I have also made the download script more robust in cases of download failures. Can you try again?
