### ISSUE TITLE
Unretire R-V8 in Fedora?

### ISSUE THREAD

**Issue by jeroen** [jeroen/V8#159]
It looks like R-V8 was [automatically retired](https://pagure.io/releng/issue/10970
) at the release of Fedora-37, due to a problem with the nodejs preview version in F37, which is now fixed: https://github.com/jeroen/V8/issues/158#issuecomment-1329751478. It would be nice to "un-retire" R-V8 in F37.

See also https://src.fedoraproject.org/rpms/R-V8/commits/rawhide

@QuLogic would you be able to help?

**Comment by QuLogic** [comment]
It unfortunately requires a re-review at this point; I have already opened one https://bugzilla.redhat.com/show_bug.cgi?id=2142712

**Comment by jeroen** [comment]
Thanks for being on it. Should we ask @sgallagher or @enchufa2 to leave a quick review? It seems there are no big changes since the previous version 3 months ago?

**Comment by Enchufa2** [comment]
Done.

**Comment by QuLogic** [comment]
Thanks @Enchufa2!

**Comment by QuLogic** [comment]
Update submitted: https://bodhi.fedoraproject.org/updates/FEDORA-2022-376a50a2fb

**Comment by jeroen** [comment]
Thanks so much @QuLogic !
