### ISSUE TITLE
Note when running `rhub::check_for_cran()`

### ISSUE THREAD

**Issue by tenderle** [jeroen/V8#164]
Hi Jeroen,

I am using `\deqn{}` in a r-package and when I run `rhub::check_for_cran()` I get the following note:

> Platform:	 Windows Server 2022, R-devel, 64 bit
> ...
> * checking HTML version of manual ... NOTE
> Skipping checking math rendering: package 'V8' unavailable

Can I ignore this issue (because it is on R-devel, R 4.3)? My local R CMD check and the Win-Builder Check (R-release, 4.2.2) have no such a note. Or do I have to address this issue to the maintainers of **rhub**?

Thanks in advance,
Tobias

**Comment by jeroen** [comment]
You can ignore it, it is unrelated to your pacakge.
