### ISSUE TITLE
Unable to load dagitty after upgrade from Fedora 36 to 37

### ISSUE THREAD

**Issue by acro2017** [jeroen/V8#165]
Dear Jeroen

Johannes Textor suggested I tried contacting you on the following matter.

I upgraded from Fedora 36 to 37 on Monday.

On 36, I had successfully installed dagitty, which was working well. After upgrade, I found that library(dagitty) on R failed to load the library.

There seems to be a compilation failure during build of V8, but I wonder if there is a version incompatibility between nodejs and v8 libraries.

I've looked and the system libraries v8-devel and nodejs* are installed:

[****]$ dnf list --installed v8*
Installed Packages
v8-devel.x86_64                   2:10.2.154.13-1.18.7.0.1.fc37                    @fedora
[****]$ dnf list --installed nodejs*
Installed Packages
nodejs.x86_64                                1:18.7.0-1.fc37                      @fedora 
nodejs-devel.x86_64                          1:18.7.0-1.fc37                      @fedora 
nodejs-docs.noarch                           1:18.7.0-1.fc37                      @fedora 
nodejs-full-i18n.x86_64                      1:18.7.0-1.fc37                      @fedora 
nodejs-libs.x86_64                           1:18.7.0-1.fc37                      @fedora 
nodejs-packaging.noarch                      2023.03-1.fc37                       @updates
[dm@HERMES ~]$

Below is the output from R on attempting to install dagitty, then V8...

> install.packages('dagitty')
Installing package into ‘/home/dm/R.LIB’
(as ‘lib’ is unspecified)
--- Please select a CRAN mirror for use in this session ---
trying URL 'https://cran.ma.imperial.ac.uk/src/contrib/dagitty_0.3-1.tar.gz'
Content type 'application/x-gzip' length 132745 bytes (129 KB)
==================================================
downloaded 129 KB

* installing *source* package ‘dagitty’ ...
** package ‘dagitty’ successfully unpacked and MD5 sums checked
** using staged installation
** R
** inst
** byte-compile and prepare package for lazy loading
Error in dyn.load(file, DLLpath = DLLpath, ...) : 
  unable to load shared object '/home/dm/R.LIB/V8/libs/V8.so':
  libnode.so.93: cannot open shared object file: No such file or directory
Calls: <Anonymous> ... namespaceImport -> loadNamespace -> library.dynam -> dyn.load
Execution halted
ERROR: lazy loading failed for package ‘dagitty’
* removing ‘/home/dm/R.LIB/dagitty’
* restoring previous ‘/home/dm/R.LIB/dagitty’

The downloaded source packages are in
        ‘/tmp/RtmppMpxNG/downloaded_packages’
Warning message:
In install.packages("dagitty") :
  installation of package ‘dagitty’ had non-zero exit status
> install.packages('V8')
Installing package into ‘/home/dm/R.LIB’
(as ‘lib’ is unspecified)
trying URL 'https://cran.ma.imperial.ac.uk/src/contrib/V8_4.2.2.tar.gz'
Content type 'application/x-gzip' length 683134 bytes (667 KB)
==================================================
downloaded 667 KB

* installing *source* package ‘V8’ ...
** package ‘V8’ successfully unpacked and MD5 sums checked
** using staged installation
Found C++17 compiler: g++
Using CXXCPP=g++ -std=gnu++17 -E
Using PKG_CFLAGS=-I/usr/include/v8 -I/usr/include/v8-3.14
Using PKG_LIBS=-lv8 -lv8_libplatform
Running feature test for pointer compression...
Pointer compression not needed
** libs
rm -f V8.so RcppExports.o bindings.o
g++ -std=gnu++17 -I"/usr/include/R" -DNDEBUG -I/usr/include/v8 -I/usr/include/v8-3.14 -DV8_ENABLE_CHECKS -DISNODEJS=10.2.154.13-node.9 -I'/home/dm/R.LIB/Rcpp/include' -I/usr/local/include  -fvisibility=hidden -fpic  -O2  -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -m64  -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection  -c RcppExports.cpp -o RcppExports.o
g++ -std=gnu++17 -I"/usr/include/R" -DNDEBUG -I/usr/include/v8 -I/usr/include/v8-3.14 -DV8_ENABLE_CHECKS -DISNODEJS=10.2.154.13-node.9 -I'/home/dm/R.LIB/Rcpp/include' -I/usr/local/include  -fvisibility=hidden -fpic  -O2  -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -m64  -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection  -c bindings.cpp -o bindings.o
bindings.cpp: In function ‘Rcpp::RObject convert_object(v8::Local<v8::Value>)’:
bindings.cpp:226:34: error: invalid use of ‘v8::Data::Data’
  226 |     memcpy(data.begin(), buffer->Data(), data.size());
      |                                  ^~~~
bindings.cpp: In function ‘bool write_array_buffer(Rcpp::String, Rcpp::RawVector, ctxptr)’:
bindings.cpp:333:18: error: invalid use of ‘v8::Data::Data’
  333 |   memcpy(buffer->Data(), data.begin(), data.size());
      |                  ^~~~
make: *** [/usr/lib64/R/etc/Makeconf:178: bindings.o] Error 1
ERROR: compilation failed for package ‘V8’
* removing ‘/home/dm/R.LIB/V8’
* restoring previous ‘/home/dm/R.LIB/V8’

The downloaded source packages are in
        ‘/tmp/RtmppMpxNG/downloaded_packages’
Warning message:
In install.packages("V8") :
  installation of package ‘V8’ had non-zero exit status
> 

Any help you can offer with this problem will be appreciated.

Best wishes

David Max

**Comment by jeroen** [comment]
This is a very old topic, but you need to reinstall the V8 R package after upgrading Fedora (because this new fedora has a newer version of libv8).
