### ISSUE TITLE
Andivirus identifies a file in V8 as infected with `Script:SNH-gen [Drp]`

### ISSUE THREAD

**Issue by GegznaV** [jeroen/V8#167]
While trying to update `V8` from CRAN, 
![image](https://user-images.githubusercontent.com/12725868/231585594-282cbb20-3088-413d-8eb3-8ba7b55c4cc5.png)

the antivirus identifies a JS file as infected
![image](https://user-images.githubusercontent.com/12725868/231585402-dc30aaf0-8e35-4cd7-920c-2a4733df5feb.png)

So the installation fails. Is this behavior expected? Is that file really safe? Why is it needed?

**Comment by jeroen** [comment]
It's just a common javascript library. Your AV must be off.
