### ISSUE TITLE
DOWNLOAD_STATIC_LIBV8=1 not working on RHEL 8 install of R

### ISSUE THREAD

**Issue by BrittSys** [jeroen/V8#174]
Hi all,

Having a hard time getting the V8 package installed into our RHEL 8 environment. I saw that there was the option to get the static package but my console keeps returning the same failures whether the var is set or not. Attaching the errored output below when attempting the install.packages("gt") command:

Error in curl::curl_download("http://jeroen.github.io/V8/get-v8-linux.sh",  :
  Timeout was reached: [] Connection timed out after 10000 milliseconds
Execution halted
Using CXXCPP=g++ -std=gnu++17 -E
Using PKG_CFLAGS=-I/usr/include/v8
Using PKG_LIBS=-lv8 -lv8_libplatform
-----------------------------[ ANTICONF ]-------------------------------
Configuration failed to find the libv8 engine library. Try installing:
 * deb: libv8-dev or libnode-dev (Debian / Ubuntu)
 * rpm: v8-devel (Fedora, EPEL)
 * brew: v8 (OSX)
 * csw: libv8_dev (Solaris)
Alternatively, on Linux (x86_64) or MacOS you can set environment variable:
    DOWNLOAD_STATIC_LIBV8=1
to automatically download a static version of libv8.
To use a custom libv8, set INCLUDE_DIR and LIB_DIR manually via:
R CMD INSTALL --configure-vars='INCLUDE_DIR=... LIB_DIR=...'
---------------------------[ ERROR MESSAGE ]----------------------------
<stdin>:1:10: fatal error: v8.h: No such file or directory
compilation terminated.
------------------------------------------------------------------------
ERROR: configuration failed for package ‘V8’
* removing ‘/RStudio_Dev_Vol2/RStudio_DEV/R-4.3.2/lib64/R/library/V8’
ERROR: dependency ‘V8’ is not available for package ‘juicyjuice’
* removing ‘/RStudio_Dev_Vol2/RStudio_DEV/R-4.3.2/lib64/R/library/juicyjuice’
ERROR: dependency ‘juicyjuice’ is not available for package ‘gt’
* removing ‘/RStudio_Dev_Vol2/RStudio_DEV/R-4.3.2/lib64/R/library/gt’
`

As mentioned DOWNLOAD_STATIC_LIBV8 is set to 1 and I can see that with a Sys.getenv() command, however the installation continues to fail.

Please let me know what the issue is if I am missing a configuration anywhere.

**Comment by jeroen** [comment]
It looks like your internet connection is blocking the download?

**Comment by mtkennedy23** [comment]
Possibly same issue as parent: I'm working with RHEL 8 in an environment where absolutely no outgoing HTTP connections are allowed, so the configure line
`${R_HOME}/bin/R -s -e 'curl::curl_download("http://jeroen.github.io/V8/get-v8-linux.sh","get-v8-linux.sh")' && . ./get-v8-linux.sh || true`
times out for my customers. I manually obtained the appropriate tar.gz over HTTPS and extracted to a semi-permanent location, and instructed my customers to avail themselves of the V8_PKG_LIBS and V8_PKG_CFLAGS variables, either in Sys.setenv() or in the configure.vars param in install.packages().

**Comment by jeroen** [comment]
Thanks. See also this issue: https://github.com/jeroen/V8/issues/168#issuecomment-2061643930
