### ISSUE TITLE
Cryptic error/warning message on install [Ubuntu 16.04]

### ISSUE THREAD

**Issue by ivso** [jeroen/V8#27]
While updating a bunch of packages it turned out that `V8` needs to be installed as a new dependency. I installed `libv8-dev` as suggested (i.e., `libv8-dev (3.14.5.8-5ubuntu2)` as provided by Ubuntu 16.04), and the repeated install seems to be successful, but I noticed the following message:

```
<snip>
Package libv8 was not found in the pkg-config search path.
Perhaps you should add the directory containing `libv8.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libv8' found
Using PKG_CFLAGS=
Using PKG_LIBS=-lv8
** libs <snip>
```

I find this message somewhat cryptic and although the package seems to have been built OK, I am not sure if some problems remain... For example, `libv8.pc` is not found in any of the packages provided by Ubuntu; similarly, there is no package named `libv8` in the repository.

**Comment by jeroenooms** [comment]
This is just some output from `pkg-config` if `libv8.pc` is not found, so the script has to "guess" the `CFLAGS` and `LIBS`. If install succeeds, you can safely ignore this message.
