### ISSUE TITLE
increase memory limit?

### ISSUE THREAD

**Issue by ateucher** [jeroen/V8#33]
I know node has the `--max_old_space_size` flag to increase the memory available. I don't know if this is possible in plain V8, particularly this version? But if so, it would be really helpful to be able to set a higher memory limit when you launch a new V8 context in R.

**Comment by jeroenooms** [comment]
I was not aware that V8 puts any memory restrictions. Should we call `max_old_space_size` by default on all contexts?

**Comment by jeroenooms** [comment]
There does seem to be an API `ResourceConstraints::set_max_old_space_size` but I don't understand how to use it. If it applies globally or per context.

**Comment by ateucher** [comment]
I do run into sometimes (I think the limit might be 512MB but I can't right now remember where I saw that). I use it in [rmapshaper](https://GitHub.com/ateucher/rmapshaper) and some spatial objects get pretty big (especially when converted to geojson) and I get out of memory errors. I'll put together an example and post it here.

**Comment by ateucher** [comment]
```r
library(readr)
library(V8)

bec <- read_file("https://dl.dropboxusercontent.com/u/18078155/bec.geojson")

ctx <- v8()
ctx$assign("bec", bec)

#
# Fatal error in CALL_AND_RETRY_0
# Allocation failed - process out of memory
#

# Abort trap: 6
```

As for user-facing options, I was thinking of argument in `V8::v8()` where it could be set (probably default `NULL` to use the default V8 memory size).

**Comment by layik** [comment]
I can confirm [above](https://github.com/jeroen/V8/issues/33#issuecomment-274297330) happens with 1.01GB data file using fresh V8 package install.

**Comment by jeroen** [comment]
Hopefully this will be fixed with new libv8: https://github.com/jeroen/V8/issues/48

**Comment by ateucher** [comment]
This isn't fixed with the new libv8 I'm afraid. @jeroen you can reopen this, or decide it's not worth fixing - I'd be fine with that - but thought I should follow up:

```
R version 3.6.0 (2019-04-26) -- "Planting of a Tree"
Copyright (C) 2019 The R Foundation for Statistical Computing
Platform: x86_64-apple-darwin15.6.0 (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

  Natural language support but running in an English locale

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.


Attaching package: 'testthat'

The following objects are masked from 'package:devtools':

    setup, test_file

> library(V8)
Using V8 engine 7.2.502.24
>
> url <- "https://dl.dropboxusercontent.com/s/e4ca5hj5y4i48aq/bec.geojson"
> tmp <- tempfile(fileext = ".geojson")
> download.file(url, tmp)
trying URL 'https://dl.dropboxusercontent.com/s/e4ca5hj5y4i48aq/bec.geojson'
Content type 'text/plain; charset=utf-8' length 770858348 bytes (735.1 MB)
==================================================
downloaded 735.1 MB

>
> bec_json <- readLines(tmp)
>
> ctx <- V8::v8()
> ctx$assign("bec", bec_json)

 *** caught segfault ***
address 0x7fbb59c00000, cause 'memory not mapped'
```
