### ISSUE TITLE
Packaging r-cran-v8 for Debian

### ISSUE THREAD

**Issue by lepalom** [jeroen/V8#35]
Hi,

I have tried to package this project for Debian and ftp-masters rejected because 
"V8/inst/doc/v8_intro.html doesn't really look like the preferred form for 
modifications"

So please, could you provide the real source of this file?

**Comment by jeroen** [comment]
This document is autogenrated from [v8_intro.Rmd](https://github.com/jeroen/V8/blob/master/vignettes/v8_intro.Rmd). You may exclude the `inst/doc` directory from the debian package. Perhaps look how this is solved in `r-cran-curl` and `r-cran-openssl` and `r-cran-jsonlite` which have the same type of documentation?

**Comment by lepalom** [comment]
Thank. I'll check what's going on with this.

**Comment by jeroen** [comment]
OK let me know what I can do to help.

**Comment by jeroen** [comment]
Make sure you `Depends: libv8-3.14-dev` because other versions of `libv8` don't work.

**Comment by lepalom** [comment]
good point, I put libv8-dev (<= 3.15)

It's ok for you?

**Comment by jeroen** [comment]
Hmz better would be specifically referencing the debian package [`libv8-3.14-dev`](https://packages.debian.org/sid/libv8-3.14-dev) I think.

**Comment by jeroen** [comment]
Seems done: https://packages.debian.org/sid/r-cran-v8
