### ISSUE TITLE
SyntaxErrors

### ISSUE THREAD

**Issue by gynt** [jeroen/V8#42]
Dear Jeroen,

I followed your suggestions on NPM and the V8 package: bundling it with `browserify`.   
I tried to do the same with the `neataptic` package.  
However, when sourcing in R, I get a syntax error: 
```
Error in context_eval(join(src), private$context) : 
  SyntaxError: Unexpected token ;
```

Before using browserify, I tried to source it directly from the browser distribution found [here](https://raw.githubusercontent.com/wagenaartje/neataptic/master/dist/neataptic.js). However, I get another syntax error:
```
Error in context_eval(join(src), private$context) : 
  SyntaxError: Unexpected token this
```
I presume something is wrong with parsing, but the javascript is technically valid.

Best,

Gynt

**Comment by jeroen** [comment]
I can't say whats wrong without seeing your javascript code. However I suspect that your code is using "modern" javascript. This package uses V8 3.14 which implements ECMA-262, 5th edition.

You could try transpiling your code using babel.js

**Comment by jeroen** [comment]
This will probably be fixed with https://github.com/jeroen/V8/issues/48

**Comment by gynt** [comment]
Awesome!
