### ISSUE TITLE
libc++ too short

### ISSUE THREAD

**Issue by Melirax** [jeroen/V8#52]
Hi, 

I am trying to install V8 package on a machine running Manjaro Linux. All is updated.
I get the following error message (either installing from CRAN or github): /lib/libc++.so: file too short.
I have tried to re-install libc++, then compiled it from source but it doesn't solve the issue. 

Any idea ?

Thanks

**Comment by jeroen** [comment]
This is a bug in the v8 library on Arch Linux. You need to report this to the Arch/Manjaro maintainers, I don't think I can help with that unfortunately.

**Comment by Melirax** [comment]
Ok thanks

**Comment by jeroen** [comment]
This person seems to have found a workaround: https://github.com/ropensci/geojsonio/issues/143#issuecomment-462378725

**Comment by jeroen** [comment]
AUR now has a v8-r package that you can use on Arch: https://aur.archlinux.org/packages/v8-r/

**Comment by Beloin** [comment]
If I may add to the thread, using ` ln -fns libc++.so.1 libc++.so ` in `usr/lib` fixed my problem

**Comment by Beloin** [comment]
Thanks @JanMarvin I should've made it clear that it could potentially break your system. My manjaro is a frankstein, so It wouldn't bother me. Somehow my latest `pacman -Syu` didn' fix this, so I went there and fixed myself (probably opening doors to new problems). It worked (for now).

To anyone who is reading this later by clicking on Google: DO NOT DO THIS IF YOU DON'T KNOW WHAT ARE YOU DOING

Even if you know what you are doing, try to update using your system's package manager.
