### ISSUE TITLE
Jquery Integration

### ISSUE THREAD

**Issue by Timag** [jeroen/V8#53]
Am I correct assuming a jquery integration is not possible?

**Comment by jeroen** [comment]
What does that mean?

**Comment by Timag** [comment]
I made an edit. If its just a bad question we can also delete it ;)

**Comment by jeroen** [comment]
I don't think there is any sensible way to use jQuery, because it is specifically made for manipulating the dom and ajax requests. Neither of those are available in vanilla V8.

Maybe you can look at underscore.js instead of jquery? It also has an extend function.

```r
library(V8)
ctx <- V8::v8()
ctx$source("https://cdnjs.cloudflare.com/ajax/libs/underscore.js/1.9.1/underscore-min.js")
ctx$eval('var object1 = {
  badDay: 0,
};
var object2 = {
  badDay: 99
};
var out = _.extend( object1, object2 );')
ctx$get('out')
```

**Comment by Timag** [comment]
Thank you, that answers my quesiton. Like i wrote "extend" is just an example from a long script, but i didnt consider underscore as a jquery alternative. I will take a look at it, otherwise it might just be the best idea to do it from scratch.
Thank you for your time!
