### ISSUE TITLE
knitr engine to run JS programs

### ISSUE THREAD

**Issue by gvwilson** [jeroen/V8#54]
It would be helpful if V8 provided a knitr engine so that JavaScript code blocks in R Markdown documents could be executed locally and immediately using Node libraries, rather than by a browser/in a web page. `reticulate` defines its own engine for executing Python chunks; it seems like V8 could do something similar (?).

Note that there is a `node` engine listed in https://bookdown.org/yihui/rmarkdown/language-engines.html, which according to Yihui essentially runs code using `system('node -e CODE')`.

**Comment by dereckmezquita** [comment]
I see this as closed completed but I am strugling to find documentation on how to actually implement this in a Rmd file? My goal is to run JS/TS code in Rmd the same way I would run R.
