### ISSUE TITLE
DiagrammeRsvg::export_svg() aborts R session 

### ISSUE THREAD

**Issue by majazaloznik** [jeroen/V8#66]
I'm not sure if I know how to give you enough information, or if you're the right person, but a lot of googling paths get me to this repo, so hopefully you can help:

I'm running manjaro, R 3.6.1, RStudio 1.2.1335, DiagrammeRsvg 0.1. 
I had  trouble installing DiagrammeRsvg, which turned out was because I also couldn't install V8 (2.3) in R, but managed finally by running `yay -S v8-3.14-bin`, after that `install.packages("V8")` worked OK, as did installing `DiagrammeRsvg`. (NB: installing v8-3.1.4 didn't work and was rolled back - but see below for the error it produced)

I then try to do use `export_svg` and it crashes R...
If i do:
```
debugonce(export_svg)
export_svg(grViz(make.dot)))
```
I see it gets to the line `ct <- new_context("window")` and then it crashes. Any pointers would be appreciated!

I case it is useful, when installing v8-3.14 I get the following error:
```
In function ‘char* strncpy(char*, const char*, size_t)’,
    inlined from ‘void v8::internal::Thread::set_name(const char*)’ at ../src/platform-linux.cc:762:10,
    inlined from ‘v8::internal::Thread::Thread(const v8::internal::Thread::Options&)’ at ../src/platform-linux.cc:735:11:
/usr/include/bits/string_fortified.h:106:34: error: ‘char* __builtin_strncpy(char*, const char*, long unsigned int)’ specified bound 16 equals destination size [-Werror=stringop-truncation]
  106 |   return __builtin___strncpy_chk (__dest, __src, __len, __bos (__dest));
      |          ~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1plus: all warnings being treated as errors
make[1]: *** [tools/gyp/v8_base.target.x64.mk:226: /home/mz/.cache/yay/v8-3.14/src/v8-3.14.5/out/x64.release/obj.target/v8_base/src/platform-linux.o] Error 1
make[1]: Leaving directory '/home/mz/.cache/yay/v8-3.14/src/v8-3.14.5/out'
make: *** [Makefile:179: x64.release] Error 2
==> ERROR: A failure occurred in build().
    Aborting...
```

**Comment by jeroen** [comment]
This is due to problems with libv8 on Arch Linux. Please search the issue tracker for solutions (I think you need another version of libv8): https://github.com/jeroen/V8/issues?utf8=%E2%9C%93&q=is%3Aissue+arch

**Comment by jeroen** [comment]
AUR now has a v8-r package: https://aur.archlinux.org/packages/v8-r/
