### ISSUE TITLE
Linux support for V8 with ES6

### ISSUE THREAD

**Issue by ijlyttle** [jeroen/V8#68]
First and foremost, thanks for this package! 

I wanted to ask about this note:

https://ropensci.org/technotes/2019/02/11/v8-20/

> If you write R packages with JS bindings, note that some Linux systems will still be running the legacy 3.14 engine for now. Hence to release the package on CRAN, you still need to use a fallback polyfill or transpile your modern JS to traditional JS something like babel.js to support legacy ES5 engines.

I realize that you are constrained by what is available "out there"; and I hope you'll forgive a "when will it be ready question".

That being said, do you have any visibility on when modern engines might be available on the remaining Linux platforms? I ask because I am working with some ES6 libraries that are resisting our efforts to transpile.

**Comment by jeroen** [comment]
What OS are you using? Latest versions on Fedora, Debian, and Ubuntu have recent engines.

Also I have a PPA with a backport for Ubuntu 18.04.

**Comment by ijlyttle** [comment]
Hopefully, this can provide some more context. Of course, I hold out the possibility that I an doing "something wrong".

I am using Ubuntu, using [libv8-dev](https://packages.ubuntu.com/bionic/libv8-dev). 

The test case I am running is something like this:

```r
library("V8")

ctx <- v8()
ctx$eval("let foo = 123") 
foo <- ctx$get("foo")
```

This code runs fine on my Mac.

There are two places I am using Ubuntu:

### RStudio Cloud (16.04)

Here, I get:

```
Error in context_eval(join(src), private$context) : 
  SyntaxError: Unexpected identifier
```

All I can do here is `install.packages("V8")`; I do not have sudo access, so I don't know which V8 it is using. Is there a way I can tell?

Looking at [another RStudio Cloud question](https://community.rstudio.com/t/install-tesseraact-in-rstudio-cloud/24182), this may be a matter of RStudio updating their image - hence the question about being able to tell which V8 it is using.

### Travis (16.04)

Here, I have tried to mirror your setup for this package, adding to `.travis.yml` [[link](https://github.com/vegawidget/ggvega/blob/f88a42adbe631456b7b1cef683239e704f6bbdfa/.travis.yml#L18)]:

```yaml
addons:
  apt:
    packages:
      - libv8-dev       # for V8
      - valgrind        # for V8
```

Then I wrap the example code in a test [[link](https://github.com/vegawidget/ggvega/blob/f88a42adbe631456b7b1cef683239e704f6bbdfa/tests/testthat/test-00-v8.R#L1)]. This test fails on Travis.

**Comment by jeroen** [comment]
You're not doing something wrong, Ubuntu 16.04 still has the old V8. You need at least 18.04.

**Comment by ijlyttle** [comment]
Thanks! On one level, it's a relief to have identified the problem. 

As you suggest, getting the transpiling to work seems the best way forward - at least until RStudio Cloud move to 18.04.

If I understand correctly, the problem will "go away" once people enough move away from earlier linux distributions. That day is not today, and it is likely not next week :)
