### ISSUE TITLE
V8 installation error

### ISSUE THREAD

**Issue by butellyn** [jeroen/V8#82]
I tried to install rmapshaper, but it failed due to being dependent on V8. Have you run into this before? And how did you fix it? Below is the error message.
<img width="737" alt="v8error" src="https://user-images.githubusercontent.com/41019524/73017795-6426da00-3dee-11ea-986a-aaf5b2d5c1d8.png">

Then I tried installing with V8 with brew, which also failed (`brew install v8`):
<img width="1125" alt="v8errorbrew" src="https://user-images.githubusercontent.com/41019524/73017827-71dc5f80-3dee-11ea-83db-4bc0174ba284.png">
<img width="909" alt="v8errorbrew2" src="https://user-images.githubusercontent.com/41019524/73017840-76a11380-3dee-11ea-86c3-6076d454f37e.png">

**Comment by jeroen** [comment]
You seem to have a broken homebrew installation. But the problem will solve itself automatically in 24h as the binaries for V8 will appear on CRAN, so you don't have to compile from source.

For now you can do: `install.packages('V8', type = 'binary')` that will give you the latest binary.
