### ISSUE TITLE
Installation fails Ubuntu 19.10 with libv8-dev, but libnode-dev works

### ISSUE THREAD

**Issue by karldw** [jeroen/V8#83]
As I said in the title, I've found that V8 works when I have libnode-dev installed, but not libv8-dev.
Feel free to close this issue, since mitigation is pretty easy. I just wanted to be sure you were aware. Thanks!

Here are the installation configurations I've tried:
- Using libv8-dev:
  - From CRAN, V8 v3.0.1: installs without error, but raises an error when I run `V8::v8()`
  - From github, b57fc9c: fails to install
- Using libnode-dev:
  - Installs and works correctly with CRAN or github versions

In all errors, the message is:
```
#
# Fatal error in ../src/platform-linux.cc, line 782
# CHECK_EQ(0, result) failed
#   Expected: 0
#   Found: 22
#

==== Stack trace is not available ==========================


==== Isolate for the thread is not initialized =============

Trace/breakpoint trap (core dumped)
```

I'm using Ubuntu 19.10 (eoan). The available development packages are libv8-dev `3.14.5.8-11ubuntu1` and libnode-dev `10.15.2~dfsg-2ubuntu1`. I uninstalled libv8-dev before installing libnode-dev.

**Comment by jeroen** [comment]
I think you had an old version of libv8 installed? A while ago the old `libv8-dev` was dropped from debian/ubuntu and `libnode-dev` now provides `libv8-dev`.

I'm quite sure this problem no longer exists if you do a clean install of ubuntu 19.10 or 20.04.
