### ISSUE TITLE
installation on RHEL 8 fails

### ISSUE THREAD

**Issue by sangarole** [jeroen/V8#84]
We have installed EPEL for RHEL 8 as well and tried installling v8-devel package. but getting errors.

**Comment by jeroen** [comment]
Yes I know, Redhat failed to include `v8-devel` in CentOS 8. @sgallagher has told me they plan to do this for RHEL 8.2 ?

**Comment by jeroen** [comment]
__Update__: `v8` is still not available in the main EPEL, however @sgallagher has helped us by making v8 available in the `nodejs:13` module repository via EPEL. 

So in RHEL / CentOS 8 you can now do:

```sh
  yum -y install epel-release 
  yum -y module enable nodejs:13
  yum -y install v8-devel
```

And after that you will be able to install the V8 R package!

**Comment by sgallagher** [comment]
Slight correction: after `yum -y install epel-release`, you also need to do `yum -y update epel-release` because the copy of that package in the CentOS repo is old and is missing the modular repository definitions.

**Comment by jeroen** [comment]
I tested the above and it worked. I think if you ran `yum update` recently then `yum install` will already get you the latest version.

**Comment by krlmlr** [comment]
I received this today:

> Package V8 no longer installs on fedora-clang after upgrading to Fedora 32.
> 
> Packages
> 
> codemetar datarobot dccvalidator dm dqshiny ggforce mcmcabn shinyMobile sparrpowR textplot
> 
> suggest it or a package which requires it but do not use it conditionally (see §1.1.3.1 of 'Writing R Extensions').
> 
> Please correct ASAP and before June 30 to safely retain the package on CRAN.

**Comment by jeroen** [comment]
This is unrelated to the above issue. It means that you have V8 as a `Suggets` (directly or indirectly) but you are not checking if it is installed, causing to fail CMD check. You have two options:
  
  1. Declare V8 (or the package that uses V8) a hard dependency via Imports.
  2. Rework your code to make sure that it will still pass CMD check if V8 is not installed.

**Comment by krlmlr** [comment]
Thanks. The warning is triggered only because V8 can't be installed. I suspect it's hard to persuade CRAN's machines to play well with V8, this means we need to use https://github.com/r-lib/roxygen2/pull/993 :smirk:

**Comment by jeroen** [comment]
You can just wrap your example in 

```r
if(require("V8")({
 # code that requires v8
}

**Comment by krlmlr** [comment]
That's what the pull request does for me, while keeping the examples tidy.
