### ISSUE TITLE
fail to install V8

### ISSUE THREAD

**Issue by LLLLUM** [jeroen/V8#91]
Thank you for your continuous development and maintenance, but recently I encountered some problems during installation.Here is the information about the error. Hope to get an answer.

`Bioconductor version 3.11 (BiocManager 1.30.10), R 4.0.0 (2020-04-24)
Installing package(s) 'V8'
trying URL 'https://mirrors.e-ducation.cn/CRAN/src/contrib/V8_3.1.0.tar.gz'
Content type 'application/x-gzip' length 680306 bytes (664 KB)
==================================================
downloaded 664 KB

* installing *source* package ‘V8’ ...
** package ‘V8’ successfully unpacked and MD5 sums checked
** using staged installation
Using PKG_CFLAGS=-I/usr/include/v8 -I/usr/include/v8-3.14
Using PKG_LIBS=-lv8 -lv8_libplatform
-----------------------------[ ANTICONF ]-------------------------------
Configuration failed to find the libv8 engine library. Try installing:
 * deb: libv8-dev or libnode-dev (Debian / Ubuntu)
 * rpm: v8-devel (Fedora, EPEL)
 * brew: v8 (OSX)
 * csw: libv8_dev (Solaris)
To use a custom libv8, set INCLUDE_DIR and LIB_DIR manually via:
R CMD INSTALL --configure-vars='INCLUDE_DIR=... LIB_DIR=...'
---------------------------[ ERROR MESSAGE ]----------------------------
<stdin>:1:10: fatal error: v8.h: No such file or directory
compilation terminated.
------------------------------------------------------------------------
ERROR: configuration failed for package ‘V8’
* removing ‘/root/miniconda2/lib/R/library/V8’

The downloaded source packages are in
	‘/tmp/RtmpaiIlr7/downloaded_packages’
Updating HTML index of packages in '.Library'
Making 'packages.html' ... done
Warning message:
In install.packages(...) :
  installation of package ‘V8’ had non-zero exit status`

**Comment by jeroen** [comment]
What OS are you on?

**Comment by LLLLUM** [comment]
my os is ubuntu18.04.4.and thank you bery much for you advice ,the problem is solved by conda install r-v8.
best wishes for you!

**Comment by aakhmetz** [comment]
```conda install r-v8``` is currently only for r=3.6, not for r=4.0.2, so this did not work for me

**Comment by aakhmetz** [comment]
Finally I installed libv8 package via conda and then V8 from R terminal - it worked
