### ISSUE TITLE
v8.h not found

### ISSUE THREAD

**Issue by fomotis** [jeroen/V8#95]
Hello @jeroen,

I tried installing V* to allow me to install rstan on a cluster, but I get the error that the header file v8.h cannot be found. I am a little less knowledgeable with Linux so what can I do to solve this problem? Thanks in advance.

Regards,
Daniel

**Comment by jeroen** [comment]
You need to `yum install v8-devel`

**Comment by mdolce8** [comment]
Hi, I am having this same issue too with installing the latest tag (V3.3.1). I am attempting to install V8 on a cluster and do not have root access. Is there some other way to install `v8-devel` so that I can successfully install V8?

**Comment by jeroen** [comment]
Can you try this:

```r
Sys.setenv(DOWNLOAD_STATIC_LIBV8 = 1)
remotes::install_github("jeroen/V8")
```

**Comment by mdolce8** [comment]
No, that did not work. In my R session, I am left with a message `Error in loadNamespace(name) : there is no package called ‘remotes’`.

**Comment by jeroen** [comment]
Maybe you can think for yourself how you would resolve that?
