### ISSUE TITLE
r_callback is broken in V8 8.7.x (V8_REVERSE_JSARGS)

### ISSUE THREAD

**Issue by JanMarvin** [jeroen/V8#96]
V8 bumped the version once again and in my weekly builds the r_callback test is broken and crashing. Not sure yet why. Results appear a bit off, e.g. ncol instead of nrow is returned

**Comment by jeroen** [comment]
This is now also a problem on homebrew 😭

**Comment by JanMarvin** [comment]
V8 devs have removed this flag a few weeks later. Can you include a flag just for homebrew?

**Comment by jeroen** [comment]
In which version was this reverted?


Op zo 29 nov. 2020 17:05 schreef Jan Marvin Garbuszus <
notifications@github.com>:

**Comment by JanMarvin** [comment]
somewhere <= 8.8.110 https://github.com/JanMarvin/v8-R/commit/c76f2b015be6c0777bd2cb20008915d083683481 this was the build I removed the flag. so either they have switched completely or ditched the idea. iirc they have already branched to 8.9 so 8.8 should be somewhat stable

**Comment by jeroen** [comment]
For future reference, the v8 team actually not reverted this, but better: they enabled but removed it as an option. So the bindings don't have to guess what the proper option is, it is just always set to enabled, both in libv8 and in the bindings.

https://chromium-review.googlesource.com/c/v8/v8/+/2466116

**Comment by JanMarvin** [comment]
Bit off topic, but if I understand [this commit](https://github.com/v8/v8/commit/553def5ffa18ba142e798513c42b626d9030aeb0) correctly, the option `v8_generate_external_defines_header=true` (in V8 9.+) will create a header with v8 build defines. (I stumbled over and had to disable the build option because of a python3 error caused by the included python script.) Maybe in the future, we can check for such includes (granted, only if they are created at build time).

**Comment by jeroen** [comment]
Interesting, thanks for mentioning this
